// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0H0pILX-P5iAaDJjnVOFP7xaGNq4Rpz4',
    appId: '1:324822870333:web:d2a9664040384f1f28fd54',
    messagingSenderId: '324822870333',
    projectId: 'doant4-ad33b',
    authDomain: 'doant4-ad33b.firebaseapp.com',
    storageBucket: 'doant4-ad33b.firebasestorage.app',
    measurementId: 'G-HT7BFNMYHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWbjGq9GNfb8Ipc1DWiMIH-uzMKofgbX0',
    appId: '1:324822870333:android:84f56175d0e5753028fd54',
    messagingSenderId: '324822870333',
    projectId: 'doant4-ad33b',
    storageBucket: 'doant4-ad33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJyV66UXj9nRweVnlRdTWKyEfzUJ5TgU4',
    appId: '1:324822870333:ios:6723293d821750d128fd54',
    messagingSenderId: '324822870333',
    projectId: 'doant4-ad33b',
    storageBucket: 'doant4-ad33b.firebasestorage.app',
    iosBundleId: 'com.example.t4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJyV66UXj9nRweVnlRdTWKyEfzUJ5TgU4',
    appId: '1:324822870333:ios:6723293d821750d128fd54',
    messagingSenderId: '324822870333',
    projectId: 'doant4-ad33b',
    storageBucket: 'doant4-ad33b.firebasestorage.app',
    iosBundleId: 'com.example.t4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0H0pILX-P5iAaDJjnVOFP7xaGNq4Rpz4',
    appId: '1:324822870333:web:de43c68f25c1c8f828fd54',
    messagingSenderId: '324822870333',
    projectId: 'doant4-ad33b',
    authDomain: 'doant4-ad33b.firebaseapp.com',
    storageBucket: 'doant4-ad33b.firebasestorage.app',
    measurementId: 'G-296SMR8GF4',
  );
}
